#!/bin/sh

set -e

if [ "$1" = configure ]; then
	if false; then
		if setcap cap_net_raw+ep /usr/bin/clockdiff; then
            chmod u-s /usr/bin/clockdiff
		else
			echo "Setcap failed on /usr/bin/clockdiff, falling back to setuid" >&2
			chmod u+s /usr/bin/clockdiff
		fi
	else
		chmod u+s /usr/bin/clockdiff
	fi
fi

#DEBHELPER#

exit 0

# Local variables:
# mode: shell-script
# tab-width: 4
# indent-tabs-mode: nil
# end:
